spring.application.name=smart-job-tracker

# MySQL configurations
spring.datasource.url=jdbc:mysql://localhost:3306/job_tracker_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=YOUR_PASSWORD_HERE

# Hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true